#Física y Medición
## Conceptos iniciales
### ¿Qué es la física?
La física es la ciencia que estudia el comportamiento de la materia, la energía y sus interacciones. Realizando mediciones y predicciones basadas en matemáticas.
### ¿Qué es la cinemática?
Es la rama de la física que estudia el movimiento de los objetos sin enfocarse en la causa de este movimiento.
### ¿Qué es el movimiento?
Es un cambio en la posición respecto a una referencia en cierto intervalo de tiempo.

---
## Mediciones
Cuando realizamos una medición en la física, tendremos errores debido a la exactitud de los instrumentos.
#### Cifras significativas
Representan la exactitud en cierta medición.
#### Convención para contar cifras significativas
A continuación se enumeran algunos consejos útiles para contar el número de cifras significativas en las cantidades.

1. Números distintos de cero son significativos. 

2. Ceros entre cifras significativas, también son significativos.

3. Ceros después del punto decimal también son significativos.

4. Los ceros antes del punto decimal y después de cifras significativas, no necesariamente son significativos.

>[!example] Ejemplo 1.1.
>¿Cuántas cifras significativas tienen las siguientes cantidades? 
>>(a) $1020\;\text{N}$ 
>>(b) $5003\;\text{kg}$
>>(c) $5.00 \;\text{m}$
>>(d) $10 000 \;\text{km}$
---
>[!note]- Solución 1.1.
>La cantidad $1020 \;\text{N}$, tiene 3 cifras significativas.
>La cantidad $5003 \;\text{kg}$, tiene 4 cifras significativas.
>La cantidad $5.00 \;\text{m}$, tiene 3 cifras significativas.
>La cantidad $10 000 \;\text{km}$, tiene una sola cifra significativa.

> [!tip]- Tips
> * Para este curso, regularmente manejaremoslas cantidades a **3 cifras significativas.**
> * Nunca olvides escribir **las unidades** en las cantidades que lo requieren.

---
## Operaciones con cifras significativas
### Multiplicación
Cuando se multipliquen o dividan dos o más cantidades, el número de cifras en el resultado, debe ser igual al número de cifras de la cantidad con menor número de cifras significativas.
### Suma o resta
Cuando los números se sumen o resten, el número de lugares decimales en el resultado debe ser igual al número más pequeño de lugares decimales de cualquier término en la suma o resta.
>[!example] Ejemplo 1.2.
>Realice las siguientes operaciones tomando en cuenta las cifras significativas de los valores iniciales.
>>(a) $25.0\,\text{m}\times2.0\,\text{m}$
>>(b) $\frac{4}{3}\pi(5.00\,\text{cm})^3$
>>(c) $12.00\,\text{N}+0.001\,\text{N}$
---
>[!note]- Solución 1.2.
>>(a) $25.0\,\text{m}\times2.0\,\text{m}=5.0\times10^1\,\text{m}^2$
>>
>> Debemos escribir el resultado a dos cifras significativas y $50\,\text{m}^2$ tiene solo una, por ello usamos notación científica. Recuerda también que las unidades también se multiplican.
>
>>(b) $\frac{4}{3}\pi(5.00\,\text{cm})^3=524\,\text{cm}^3$
>>
>> Las cantidades dadas en fórmulas se consideran como exactas, es decir tanto $\frac{4}{3}$ como $\pi$ tienen cifras infinitas.
>
>>(c) $12.00\,\text{N}+0.001\,\text{N}=12.001\,\text{N}$
>>

***
## Conversión de unidades

En cantidades de la misma naturaleza, podemos usar distintas unidades de medida que se adapten a dicha medición.

| Longitud | Masa | Tiempo |
| -------- | ---- | ------ |
|          |      |        |
### Estrategia para convertir unidades
```mermaid
---
config:
  htmlLabels: false
---
flowchart LR
    markdown["`Cantidad 
    deseada`"]
    newLines["`Cantidad
    a
    convertir`"]
    markdown --> newLines

```

$$\cancel{\text{cantidad a convertir}}=\left(\frac{\text{cantidad deseada}}{\cancel{\text{cantidad a convertir}}}\right)=\text{cantidad deseada}$$

---
