project:
  type: website

website:
  title: "Física ilustrada"
  navbar:
    background: light
    search: true 
    left:
      - href: index.qmd
        text: Home
      - href: 1_introduccion.qmd
        text: Física A
      - about.qmd
  sidebar:
  - id: Fisica-a
    title: Física A
    style: floating
    contents:
      - section: "Capítulo 1: Física y Medición"
        contents:
          - 1_introduccion.qmd
          - 1_2_vectores.qmd
      - section: "Capítulo 2: Cinemática"
        contents:
          - 2_movimiento.qmd
format:
  html:
    theme:
      light: [cosmo, brand]
      dark: [darkly, brand]
    css: styles.css
    toc: true



